service: bakery-dynamo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:us-east-1:*:table/*"

resources:
  Resources:
    ${file(serverless/resources/tables.yml)}

functions:
  ${file(serverless/functions/lambdas.yml)}
